name: zupa
description: "A zero user parking app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0-296.4.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^17.0.1
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  shared_preferences: ^2.5.4
  google_nav_bar: ^5.0.7
  google_fonts: ^8.0.0
  vector_graphics: ^1.1.19
  retrofit: ^4.9.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dio: ^5.9.1
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  loading_animation_widget: ^1.3.0
  easy_refresh: ^3.4.0
  connectivity_plus: ^7.0.0
  cached_network_image: ^3.4.1
  skeletonizer: ^2.1.2
  nfc_manager: ^4.1.1
  volume_listener:
    git:
      url: https://github.com/Tran-Duc-Nhat-Nam-270702/volume_listener.git
      ref: main
  camera: ^0.11.2+1
  upgrader: ^12.5.0
  flutter_smart_dialog: ^4.9.8+9
  animated_segmented_tab_control: ^2.0.0
  photo_view: ^0.15.0
  flutter_slidable: ^4.0.3
  dropdown_button2: ^3.0.0-beta.24
  omni_datetime_picker: ^2.3.1
  animated_toggle_switch: ^0.8.7
  animations: ^2.1.1
  page_transition: ^2.2.1
  talker: ^5.1.13
  talker_flutter: ^5.1.13
  talker_dio_logger: ^5.1.13
  shake: ^3.0.0
  flutter_native_splash: ^2.4.7
  local_auth: ^3.0.0
  flutter_local_notifications: ^20.0.0
  firebase_messaging: ^16.1.1
  firebase_core: ^4.4.0
  firebase_crashlytics: ^5.0.7
  dartx: ^1.2.0
  get_it: ^9.2.0
  injectable: ^2.7.1+4
  slang: ^4.12.0
  slang_flutter: ^4.12.0
  intl: ^0.20.2
  dart_date: ^1.5.3
  envied: ^1.3.2
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  freezed: ^3.2.4
  json_serializable: ^6.11.4
  retrofit_generator: ^10.2.1
  flutter_launcher_icons: ^0.14.4
  injectable_generator: ^2.12.0
  slang_build_runner: ^4.12.0
  envied_generator: ^1.3.2
  vector_graphics_compiler: ^1.1.20

flutter:
  uses-material-design: true
  assets:
    - path: assets/icons/
      transformers:
        - package: vector_graphics_compiler
    - path: assets/icons/vuesax/bold/
      transformers:
        - package: vector_graphics_compiler
    - path: assets/icons/vuesax/outline/
      transformers:
        - package: vector_graphics_compiler
    - path: assets/icons/vuesax/linear/
      transformers:
        - package: vector_graphics_compiler
    - assets/images/
    - assets/i18n/
