name: zupa
description: "A zero user parking app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.2.3
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  shared_preferences: ^2.5.3
  persistent_bottom_nav_bar_v2: ^6.1.0
  google_fonts: ^6.3.0
  flutter_svg: ^2.2.0
  jiffy: ^6.4.3
  retrofit: ^4.7.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dropdown_search: ^7.0.0-pre2
  dio: ^5.8.0+1
  easy_localization: ^3.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  loading_animation_widget: ^1.3.0
  jwt_decoder: ^2.0.1
  pull_to_refresh_flutter3: ^2.0.2
  internet_connection_checker_plus: ^2.7.2
  permission_handler: ^12.0.1
  cached_network_image: ^3.4.1
  skeletonizer: ^2.1.0
  nfc_manager: ^4.0.2
  volume_listener: ^0.1.0
  material_dialogs: ^1.1.5
  camera: ^0.11.2
  upgrader: ^11.4.0
  fluttertoast: ^8.2.12
  animated_segmented_tab_control: ^2.0.0
  photo_view: ^0.15.0
  animated_toggle_switch: ^0.8.5
  flutter_layout_grid: ^2.0.8
  flutter_swipe_action_cell: ^3.1.5
  dropdown_button2: ^3.0.0-beta.22
  expansion_widget: ^0.1.0
  mockito: ^5.5.0
  bloc_test: ^10.0.0
  catppuccin_flutter: ^1.0.0
  omni_datetime_picker: ^2.3.1
  shared_preferences_android: ^2.4.10
  flutter_advanced_switch:
    git:
      url: https://github.com/Tran-Duc-Nhat-Nam-270702/flutter_advanced_switch.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  retrofit_generator: ^10.0.1
  rename_app: ^1.6.5
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/vuesax/bold/
    - assets/icons/vuesax/outline/
    - assets/icons/vuesax/linear/
    - assets/images/
    - assets/translations/
