name: zupa
description: "A zero user parking app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0-93.1.beta

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.0
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  shared_preferences: ^2.5.3
  persistent_bottom_nav_bar_v2:
    git:
      url: https://github.com/Tran-Duc-Nhat-Nam-270702/PersistentBottomNavBarV2.git
      ref: master
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.3
  jiffy: ^6.4.4
  retrofit: ^4.9.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dropdown_search: ^7.0.0-pre2
  dio: ^5.9.0
  easy_localization: ^3.0.8
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  loading_animation_widget: ^1.3.0
  pull_to_refresh_flutter3: ^2.0.2
  internet_connection_checker_plus: ^2.9.1
  cached_network_image: ^3.4.1
  skeletonizer: ^2.1.1
  nfc_manager: ^4.1.1
  volume_listener:
    git:
      url: https://github.com/Tran-Duc-Nhat-Nam-270702/volume_listener.git
      ref: main
  material_dialogs: ^1.1.5
  camera: ^0.11.2+1
  upgrader: ^12.3.0
  fluttertoast: ^9.0.0
  animated_segmented_tab_control: ^2.0.0
  photo_view: ^0.15.0
  flutter_swipe_action_cell: ^3.1.6
  dropdown_button2: ^3.0.0-beta.22
  catppuccin_flutter: ^1.0.0
  omni_datetime_picker: ^2.3.1
  flutter_advanced_switch:
    git:
      url: https://github.com/Tran-Duc-Nhat-Nam-270702/flutter_advanced_switch.git
      ref: master
  animations: ^2.1.1
  page_transition: ^2.2.1
  logarte: ^1.4.0
  shake: ^3.0.0
  sensors_plus_platform_interface: ^2.0.1
  flutter_native_splash: ^2.4.7
  local_auth: ^3.0.0
  flutter_local_notifications: ^19.5.0
  firebase_messaging: ^16.0.4
  firebase_core: ^4.2.1
  firebase_crashlytics: ^5.0.5
  dartx: ^1.2.0
  auto_size_text: ^3.0.0
  string_validator: ^1.2.0
  zentoast: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  retrofit_generator: ^10.2.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/vuesax/bold/
    - assets/icons/vuesax/outline/
    - assets/icons/vuesax/linear/
    - assets/images/
    - assets/translations/
